//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectRichard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nation
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Property { get; set; }
        public string Improvements { get; set; }
        public string Units { get; set; }
        public string PowerEra { get; set; }
        public string Place { get; set; }
        public int Evaluation { get; set; }
        public string URL { get; set; }
    }
}
